name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  fmt:
    name: Terraform Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: hashicorp/setup-terraform@v4
      - name: Check formatting
        run: terraform fmt -check -recursive
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: hashicorp/setup-terraform@v4
      - name: Validate terraform configuration 
        run: terraform init && terraform validate 

  trivy:
    name: Trivy IaC (Docker)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Run Trivy (Docker)
        run: |
          docker run --rm \
            -v "$PWD":/project \
            -v ~/.cache/trivy:/root/.cache/trivy \
            -w /project \
            aquasec/trivy:latest \
            config --severity HIGH,CRITICAL --format table . > trivy-iac.txt
      - name: Upload Trivy report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-iac
          path: trivy-iac.txt

  checkov:
    name: Checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: .
          framework: terraform
          soft_fail: false
