name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  fmt:
    name: Terraform Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: hashicorp/setup-terraform@v4
      - name: Check formatting
        run: terraform fmt -check -recursive
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: hashicorp/setup-terraform@v4
      - name: Check formatting
        run: terraform validate 

  tfsec:
    name: trivysec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run Trivy IaC scan
        uses: aquasecurity/trivy-action@v1
        with:
          scan-type: iac
          directory: .
          format: table
          severity: HIGH,CRITICAL
          exit-code: '1'

  checkov:
    name: Checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: .
          framework: terraform
          soft_fail: false
